In [14]:
class Employee:
    #Create a data member to count the number of Employees
    Employees=0
    salaries=[]
    
    #Create a constructor to initialize name, family, salary, department
    def __init__(self, name, family, salary, department):
        self.name=name
        self.family=family
        self.salary=salary
        self.department=department
        #Incrementing Employee Count        
        Employee.Employees+= 1
        #Appending them to a list        
        Employee.salaries.append(self.salary)
    #Create a function to average salary
    def average_salary(self):
        return sum(Employee.salaries)/Employee.Employees   
#Create a Fulltime Employee class and it should inherit the properties of Employee class
class FulltimeEmployee(Employee):
    pass
#Create the instances of Fulltime Employee class and Employee class and call their member functions
e1=Employee("Deepu","Koundinya",30000,"IT")
e2=FulltimeEmployee("Satish","kumar",20000,"Marketing")

#Using the same function in inherited class
print(e1.average_salary())
print(e2.average_salary())

25000.0
25000.0


In [10]:
# Importing numpy library
import numpy as np
# Creating a vector of size 20 with random float values ranging between 1 to 20
vector=np.round(np.random.uniform(1,20,size=20),decimals=2)
print("Vector is ",vector)
# Reshaping the existing vector to 4*5 size
new_vector=vector.reshape(4,5)
print("Reshaped array is",new_vector)
# Replace the max in each row by 0 (without using a for loop)
final_vector=np.where(new_vector==np.max(new_vector,axis=1,keepdims=True), 0, new_vector)
print(final_vector)

Vector is  [ 6.6   2.24 10.27  9.91 12.1   5.85 16.73  9.87 13.22  5.19  6.69 11.99
  2.48 10.81  4.55 11.55 15.69 13.25  9.46  4.36]
Reshaped array is [[ 6.6   2.24 10.27  9.91 12.1 ]
 [ 5.85 16.73  9.87 13.22  5.19]
 [ 6.69 11.99  2.48 10.81  4.55]
 [11.55 15.69 13.25  9.46  4.36]]
[[ 6.6   2.24 10.27  9.91  0.  ]
 [ 5.85  0.    9.87 13.22  5.19]
 [ 6.69  0.    2.48 10.81  4.55]
 [11.55  0.   13.25  9.46  4.36]]
